trigger: none

pool:
  name: RPLocalPool
  demands:
    - agent.name -equals RPLocalMac
parameters:
  - name: targetEnvironment
    displayName: "Target Environment"
    type: string
    default: DEV
    values:
      - DEV
      - TEST
      - ACC
  - name: certificateName
    displayName: 'Certificate name as in Keyvault'
    type: string
    default: 'BMC Certificate'
stages:
  - stage: PrintfromPowershell
    displayName: 'Print from Powershell'
    jobs:
      - job: PFP
        displayName: 'Print from Powershell'
        steps:
          - pwsh: |
              Get-Location
              echo 'Value in next line'
              echo ${{ parameters.certificateName }}
              Set-Content test.txt ${{ parameters.certificateName }}
              ls
